// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Abogado
{
    public int IdAbogado { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Cedula { get; set; }

    public string Email { get; set; }

    public string Telefono { get; set; }

    public string Especialidad { get; set; }

    public bool Estado { get; set; }

    public virtual ICollection<Caso> Casos { get; set; } = new List<Caso>();

    public virtual ICollection<TiempoFacturable> TiempoFacturables { get; set; } = new List<TiempoFacturable>();
}