// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Abogado
{
    [Key]
    public int IdAbogado { get; set; }

    [StringLength(150)]
    public string Nombre { get; set; } = null!;

    [StringLength(150)]
    public string Apellido { get; set; } = null!;

    [StringLength(20)]
    public string Cedula { get; set; } = null!;

    [StringLength(100)]
    public string? Email { get; set; }

    [StringLength(50)]
    public string? Telefono { get; set; }

    [StringLength(100)]
    public string? Especialidad { get; set; }

    public bool Estado { get; set; }

    public int? IdConsultorio { get; set; }

    [InverseProperty("IdAbogadoResponsableNavigation")]
    public virtual ICollection<Caso> Casos { get; set; } = new List<Caso>();

    [InverseProperty("IdAbogadoNavigation")]
    public virtual ICollection<TiempoFacturable> TiempoFacturables { get; set; } = new List<TiempoFacturable>();
}