// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Auditoria
{
    [Key]
    public int IdAuditoria { get; set; }

    [StringLength(100)]
    public string? Usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha { get; set; }

    [StringLength(200)]
    public string? Accion { get; set; }

    [StringLength(100)]
    public string? TablaAfectada { get; set; }

    [StringLength(100)]
    public string? ClaveRegistro { get; set; }

    public string? DetalleCambio { get; set; }

    public int? IdConsultorio { get; set; }
}