// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Auditoria
{
    public int IdAuditoria { get; set; }

    public string Usuario { get; set; }

    public DateTime? Fecha { get; set; }

    public string Accion { get; set; }

    public string TablaAfectada { get; set; }

    public string ClaveRegistro { get; set; }

    public string DetalleCambio { get; set; }
}