// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class BitacoraCambio
{
    [Key]
    public int IdBitacora { get; set; }

    [StringLength(50)]
    public string? Tabla { get; set; }

    public int? IdRegistro { get; set; }

    [StringLength(100)]
    public string? UsuarioModificacion { get; set; }

    [StringLength(100)]
    public string? CampoModificado { get; set; }

    public string? ValorAnterior { get; set; }

    public string? ValorNuevo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaModificacion { get; set; }
}