// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class BitacoraCambio
{
    public int IdBitacora { get; set; }

    public string Tabla { get; set; }

    public int? IdRegistro { get; set; }

    public string UsuarioModificacion { get; set; }

    public string CampoModificado { get; set; }

    public string ValorAnterior { get; set; }

    public string ValorNuevo { get; set; }

    public DateTime? FechaModificacion { get; set; }
}