// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[Index("CodigoCaso", Name = "UQ__Casos__D30CA0E7F7B18AE7", IsUnique = true)]
public partial class Caso
{
    [Key]
    public int IdCaso { get; set; }

    [StringLength(50)]
    public string CodigoCaso { get; set; } = null!;

    [StringLength(200)]
    public string Titulo { get; set; } = null!;

    public string? Descripcion { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    [StringLength(50)]
    public string? Estado { get; set; }

    public int IdCliente { get; set; }

    public int IdAbogadoResponsable { get; set; }

    public int? IdConsultorio { get; set; }

    [InverseProperty("IdCasoNavigation")]
    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    [ForeignKey("IdAbogadoResponsable")]
    [InverseProperty("Casos")]
    public virtual Abogado IdAbogadoResponsableNavigation { get; set; } = null!;

    [ForeignKey("IdCliente")]
    [InverseProperty("Casos")]
    public virtual Cliente IdClienteNavigation { get; set; } = null!;

    [InverseProperty("IdCasoNavigation")]
    public virtual ICollection<NotasInterna> NotasInternas { get; set; } = new List<NotasInterna>();

    [InverseProperty("IdCasoNavigation")]
    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();

    [InverseProperty("IdCasoNavigation")]
    public virtual ICollection<TiempoFacturable> TiempoFacturables { get; set; } = new List<TiempoFacturable>();
}