// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Caso
{
    public int IdCaso { get; set; }

    public string CodigoCaso { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public string Estado { get; set; }

    public int IdCliente { get; set; }

    public int IdAbogadoResponsable { get; set; }

    public virtual ICollection<Documento> Documentos { get; set; } = new List<Documento>();

    public virtual Abogado IdAbogadoResponsableNavigation { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual ICollection<NotasInterna> NotasInternas { get; set; } = new List<NotasInterna>();

    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();

    public virtual ICollection<TiempoFacturable> TiempoFacturables { get; set; } = new List<TiempoFacturable>();
}