// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[Table("ChatKnowledgeBase")]
public partial class ChatKnowledgeBase
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "text")]
    public string? UserQuestion { get; set; }

    [Column(TypeName = "text")]
    public string? CleanedQuestion { get; set; }

    [Column(TypeName = "text")]
    public string? Answer { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }
}