// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Cliente
{
    [Key]
    public int IdCliente { get; set; }

    [StringLength(200)]
    public string RazonSocial { get; set; } = null!;

    [Column("RUC_Cedula")]
    [StringLength(20)]
    public string RucCedula { get; set; } = null!;

    [StringLength(150)]
    public string? RepresentanteLegal { get; set; }

    [StringLength(100)]
    public string? Correo { get; set; }

    [StringLength(50)]
    public string? Telefono { get; set; }

    [StringLength(300)]
    public string? Direccion { get; set; }

    [StringLength(20)]
    public string? TipoCliente { get; set; }

    public int? IdConsultorio { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Caso> Casos { get; set; } = new List<Caso>();

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<ContactosCliente> ContactosClientes { get; set; } = new List<ContactosCliente>();

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}