// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string RazonSocial { get; set; }

    public string RucCedula { get; set; }

    public string RepresentanteLegal { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public string TipoCliente { get; set; }

    public virtual ICollection<Caso> Casos { get; set; } = new List<Caso>();

    public virtual ICollection<ContactosCliente> ContactosClientes { get; set; } = new List<ContactosCliente>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}