// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Consultorio
{
    [Key]
    public int IdConsultorio { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Nombre { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string? Direccion { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Telefono { get; set; }

    public bool? Estado { get; set; }
}