// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[Table("ContactosCliente")]
public partial class ContactosCliente
{
    [Key]
    public int IdContacto { get; set; }

    public int? IdCliente { get; set; }

    [StringLength(100)]
    public string? Nombre { get; set; }

    [StringLength(100)]
    public string? Cargo { get; set; }

    [StringLength(100)]
    public string? Email { get; set; }

    [StringLength(50)]
    public string? Telefono { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("ContactosClientes")]
    public virtual Cliente? IdClienteNavigation { get; set; }

 
}