// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class ContactosCliente
{
    public int IdContacto { get; set; }

    public int? IdCliente { get; set; }

    public string Nombre { get; set; }

    public string Cargo { get; set; }

    public string Email { get; set; }

    public string Telefono { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }
}