// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class DetalleFactura
{
    public int IdDetalle { get; set; }

    public int? IdFactura { get; set; }

    public int? IdTiempo { get; set; }

    public decimal? Subtotal { get; set; }

    public virtual Factura IdFacturaNavigation { get; set; }

    public virtual TiempoFacturable IdTiempoNavigation { get; set; }
}