// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Documento
{
    public int IdDocumento { get; set; }

    public string NombreArchivo { get; set; }

    public string TipoDocumento { get; set; }

    public string RutaArchivo { get; set; }

    public DateTime? FechaSubida { get; set; }

    public int IdCaso { get; set; }

    public virtual Caso IdCasoNavigation { get; set; }
}