// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Documento
{
    [Key]
    public int IdDocumento { get; set; }

    [StringLength(255)]
    public string? NombreArchivo { get; set; }

    [StringLength(100)]
    public string? TipoDocumento { get; set; }

    [StringLength(500)]
    public string? RutaArchivo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaSubida { get; set; }

    public int IdCaso { get; set; }

    [ForeignKey("IdCaso")]
    [InverseProperty("Documentos")]
    public virtual Caso IdCasoNavigation { get; set; } = null!;
}