// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class HistorialAccione
{
    [Key]
    public int IdHistorial { get; set; }

    public int? IdUsuario { get; set; }

    [StringLength(100)]
    public string? Modulo { get; set; }

    [StringLength(200)]
    public string? Accion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha { get; set; }

    public string? Detalle { get; set; }

    [ForeignKey("IdUsuario")]
    [InverseProperty("HistorialAcciones")]
    public virtual Usuario? IdUsuarioNavigation { get; set; }
}