// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class HistorialAccione
{
    public int IdHistorial { get; set; }

    public int? IdUsuario { get; set; }

    public string Modulo { get; set; }

    public string Accion { get; set; }

    public DateTime? Fecha { get; set; }

    public string Detalle { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}