// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class NotasInterna
{
    public int IdNota { get; set; }

    public int? IdCaso { get; set; }

    public string Autor { get; set; }

    public DateTime? Fecha { get; set; }

    public string Nota { get; set; }

    public virtual Caso IdCasoNavigation { get; set; }
}