// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class NotasInterna
{
    [Key]
    public int IdNota { get; set; }

    public int? IdCaso { get; set; }

    [StringLength(100)]
    public string? Autor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Fecha { get; set; }

    public string? Nota { get; set; }

    [ForeignKey("IdCaso")]
    [InverseProperty("NotasInternas")]
    public virtual Caso? IdCasoNavigation { get; set; }
}