// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Tarea
{
    public int IdTarea { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public DateOnly? FechaAsignacion { get; set; }

    public DateOnly? FechaLimite { get; set; }

    public string Estado { get; set; }

    public int? IdCaso { get; set; }

    public int? IdUsuarioAsignado { get; set; }

    public virtual Caso IdCasoNavigation { get; set; }

    public virtual Usuario IdUsuarioAsignadoNavigation { get; set; }
}