// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class Tarea
{
    [Key]
    public int IdTarea { get; set; }

    [StringLength(200)]
    public string? Titulo { get; set; }

    public string? Descripcion { get; set; }

    public DateOnly? FechaAsignacion { get; set; }

    public DateOnly? FechaLimite { get; set; }

    [StringLength(50)]
    public string? Estado { get; set; }

    public int? IdCaso { get; set; }

    public int? IdUsuarioAsignado { get; set; }

    [ForeignKey("IdCaso")]
    [InverseProperty("Tareas")]
    public virtual Caso? IdCasoNavigation { get; set; }

    [ForeignKey("IdUsuarioAsignado")]
    [InverseProperty("Tareas")]
    public virtual Usuario? IdUsuarioAsignadoNavigation { get; set; }
}