// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class TiempoFacturable
{
    public int IdTiempo { get; set; }

    public int? IdCaso { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    public decimal? Horas { get; set; }

    public string Descripcion { get; set; }

    public int? IdAbogado { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Abogado IdAbogadoNavigation { get; set; }

    public virtual Caso IdCasoNavigation { get; set; }
}