// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[Table("TiempoFacturable")]
public partial class TiempoFacturable
{
    [Key]
    public int IdTiempo { get; set; }

    public int? IdCaso { get; set; }

    public DateOnly? FechaRegistro { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? Horas { get; set; }

    [StringLength(300)]
    public string? Descripcion { get; set; }

    public int? IdAbogado { get; set; }

    [InverseProperty("IdTiempoNavigation")]
    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    [ForeignKey("IdAbogado")]
    [InverseProperty("TiempoFacturables")]
    public virtual Abogado? IdAbogadoNavigation { get; set; }

    [ForeignKey("IdCaso")]
    [InverseProperty("TiempoFacturables")]
    public virtual Caso? IdCasoNavigation { get; set; }
}