// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

[Index("NombreUsuario", Name = "UQ__Usuarios__6B0F5AE06114EB70", IsUnique = true)]
public partial class Usuario
{
    [Key]
    public int IdUsuario { get; set; }

    [StringLength(50)]
    public string NombreUsuario { get; set; } = null!;

    [StringLength(200)]
    public string PasswordHash { get; set; } = null!;

    [StringLength(50)]
    public string? Rol { get; set; }

    [StringLength(100)]
    public string? Email { get; set; }

    public bool? Estado { get; set; }

    public int? IdConsultorio { get; set; }

    [InverseProperty("IdUsuarioNavigation")]
    public virtual ICollection<HistorialAccione> HistorialAcciones { get; set; } = new List<HistorialAccione>();

    [InverseProperty("IdUsuarioAsignadoNavigation")]
    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();
}