// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string NombreUsuario { get; set; }

    public string PasswordHash { get; set; }

    public string Rol { get; set; }

    public string Email { get; set; }

    public bool? Estado { get; set; }

    public virtual ICollection<HistorialAccione> HistorialAcciones { get; set; } = new List<HistorialAccione>();

    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();
}