// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Domain.Models;

public partial class AbogadosContext : DbContext
{
    public AbogadosContext(DbContextOptions<AbogadosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Abogado> Abogados { get; set; }

    public virtual DbSet<Auditoria> Auditorias { get; set; }

    public virtual DbSet<BitacoraCambio> BitacoraCambios { get; set; }

    public virtual DbSet<Caso> Casos { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<ContactosCliente> ContactosClientes { get; set; }

    public virtual DbSet<DetalleFactura> DetalleFacturas { get; set; }

    public virtual DbSet<Documento> Documentos { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<HistorialAccione> HistorialAcciones { get; set; }

    public virtual DbSet<NotasInterna> NotasInternas { get; set; }

    public virtual DbSet<Tarea> Tareas { get; set; }

    public virtual DbSet<TiempoFacturable> TiempoFacturables { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Abogado>(entity =>
        {
            entity.HasKey(e => e.IdAbogado).HasName("PK__Abogados__9C2E1F07F2B39EBF");

            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Cedula)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Especialidad).HasMaxLength(100);
            entity.Property(e => e.Estado).HasDefaultValue(true);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Telefono).HasMaxLength(50);
        });

        modelBuilder.Entity<Auditoria>(entity =>
        {
            entity.HasKey(e => e.IdAuditoria).HasName("PK__Auditori__7FD13FA0216420DC");

            entity.Property(e => e.Accion).HasMaxLength(200);
            entity.Property(e => e.ClaveRegistro).HasMaxLength(100);
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TablaAfectada).HasMaxLength(100);
            entity.Property(e => e.Usuario).HasMaxLength(100);
        });

        modelBuilder.Entity<BitacoraCambio>(entity =>
        {
            entity.HasKey(e => e.IdBitacora).HasName("PK__Bitacora__ED3A1B133530510F");

            entity.Property(e => e.CampoModificado).HasMaxLength(100);
            entity.Property(e => e.FechaModificacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Tabla).HasMaxLength(50);
            entity.Property(e => e.UsuarioModificacion).HasMaxLength(100);
        });

        modelBuilder.Entity<Caso>(entity =>
        {
            entity.HasKey(e => e.IdCaso).HasName("PK__Casos__3B7B2BDCCE62320F");

            entity.HasIndex(e => e.CodigoCaso, "UQ__Casos__D30CA0E7F7B18AE7").IsUnique();

            entity.Property(e => e.CodigoCaso)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Estado)
                .HasMaxLength(50)
                .HasDefaultValue("Abierto");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.IdAbogadoResponsableNavigation).WithMany(p => p.Casos)
                .HasForeignKey(d => d.IdAbogadoResponsable)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Casos__IdAbogado__4316F928");

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Casos)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Casos__IdCliente__4222D4EF");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.IdCliente).HasName("PK__Clientes__D5946642AF14F668");

            entity.Property(e => e.Correo).HasMaxLength(100);
            entity.Property(e => e.Direccion).HasMaxLength(300);
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.RepresentanteLegal).HasMaxLength(150);
            entity.Property(e => e.RucCedula)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("RUC_Cedula");
            entity.Property(e => e.Telefono).HasMaxLength(50);
            entity.Property(e => e.TipoCliente).HasMaxLength(20);
        });

        modelBuilder.Entity<ContactosCliente>(entity =>
        {
            entity.HasKey(e => e.IdContacto).HasName("PK__Contacto__A4D6BBFA0CF713D5");

            entity.ToTable("ContactosCliente");

            entity.Property(e => e.Cargo).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Nombre).HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(50);

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.ContactosClientes)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("FK__Contactos__IdCli__656C112C");
        });

        modelBuilder.Entity<DetalleFactura>(entity =>
        {
            entity.HasKey(e => e.IdDetalle).HasName("PK__DetalleF__E43646A562F1753A");

            entity.ToTable("DetalleFactura");

            entity.Property(e => e.Subtotal).HasColumnType("decimal(12, 2)");

            entity.HasOne(d => d.IdFacturaNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.IdFactura)
                .HasConstraintName("FK__DetalleFa__IdFac__5441852A");

            entity.HasOne(d => d.IdTiempoNavigation).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.IdTiempo)
                .HasConstraintName("FK__DetalleFa__IdTie__5535A963");
        });

        modelBuilder.Entity<Documento>(entity =>
        {
            entity.HasKey(e => e.IdDocumento).HasName("PK__Document__E52073476004EB12");

            entity.Property(e => e.FechaSubida)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.NombreArchivo).HasMaxLength(255);
            entity.Property(e => e.RutaArchivo).HasMaxLength(500);
            entity.Property(e => e.TipoDocumento).HasMaxLength(100);

            entity.HasOne(d => d.IdCasoNavigation).WithMany(p => p.Documentos)
                .HasForeignKey(d => d.IdCaso)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Documento__IdCas__46E78A0C");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.IdFactura).HasName("PK__Facturas__50E7BAF1942B3606");

            entity.Property(e => e.Estado).HasMaxLength(50);
            entity.Property(e => e.MontoTotal).HasColumnType("decimal(12, 2)");
            entity.Property(e => e.NumeroFactura).HasMaxLength(50);

            entity.HasOne(d => d.IdClienteNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.IdCliente)
                .HasConstraintName("FK__Facturas__IdClie__5165187F");
        });

        modelBuilder.Entity<HistorialAccione>(entity =>
        {
            entity.HasKey(e => e.IdHistorial).HasName("PK__Historia__9CC7DBB4BB16B06D");

            entity.Property(e => e.Accion).HasMaxLength(200);
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Modulo).HasMaxLength(100);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.HistorialAcciones)
                .HasForeignKey(d => d.IdUsuario)
                .HasConstraintName("FK__Historial__IdUsu__628FA481");
        });

        modelBuilder.Entity<NotasInterna>(entity =>
        {
            entity.HasKey(e => e.IdNota).HasName("PK__NotasInt__4B2ACFF24342BE8F");

            entity.Property(e => e.Autor).HasMaxLength(100);
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.IdCasoNavigation).WithMany(p => p.NotasInternas)
                .HasForeignKey(d => d.IdCaso)
                .HasConstraintName("FK__NotasInte__IdCas__5EBF139D");
        });

        modelBuilder.Entity<Tarea>(entity =>
        {
            entity.HasKey(e => e.IdTarea).HasName("PK__Tareas__EADE9098B269A11A");

            entity.Property(e => e.Estado).HasMaxLength(50);
            entity.Property(e => e.Titulo).HasMaxLength(200);

            entity.HasOne(d => d.IdCasoNavigation).WithMany(p => p.Tareas)
                .HasForeignKey(d => d.IdCaso)
                .HasConstraintName("FK__Tareas__IdCaso__49C3F6B7");

            entity.HasOne(d => d.IdUsuarioAsignadoNavigation).WithMany(p => p.Tareas)
                .HasForeignKey(d => d.IdUsuarioAsignado)
                .HasConstraintName("FK__Tareas__IdUsuari__4AB81AF0");
        });

        modelBuilder.Entity<TiempoFacturable>(entity =>
        {
            entity.HasKey(e => e.IdTiempo).HasName("PK__TiempoFa__69A041D197F13D13");

            entity.ToTable("TiempoFacturable");

            entity.Property(e => e.Descripcion).HasMaxLength(300);
            entity.Property(e => e.Horas).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.IdAbogadoNavigation).WithMany(p => p.TiempoFacturables)
                .HasForeignKey(d => d.IdAbogado)
                .HasConstraintName("FK__TiempoFac__IdAbo__4E88ABD4");

            entity.HasOne(d => d.IdCasoNavigation).WithMany(p => p.TiempoFacturables)
                .HasForeignKey(d => d.IdCaso)
                .HasConstraintName("FK__TiempoFac__IdCas__4D94879B");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuarios__5B65BF97306B1CEB");

            entity.HasIndex(e => e.NombreUsuario, "UQ__Usuarios__6B0F5AE06114EB70").IsUnique();

            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Estado).HasDefaultValue(true);
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Rol).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}